services:
  db1:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teamninelives
      MYSQL_DATABASE: VendingMachineDB
      MYSQL_ROOT_HOST: '%'
    volumes:
      - vendingmachinedat:/var/lib/mysql   # Persistent database storage
      - /nobackup/T_19/db/:/docker-entrypoint-initdb.d/  # Run init script on startup
    ports:
      - "3333:3306"

  backend:
    build: /nobackup/T_19/api
    restart: always
    working_dir: /app
    volumes:
      - /nobackup/T_19/api:/app
      # - /app/node_modules # ensure we are not copying node_modules from the outside
    ports:
      - "8080:5000"
    depends_on:
      - db1
    env_file:
      - /nobackup/T_19/api/.env

volumes:
  vendingmachinedat: