line-length = 100

[lint]

select = ["ALL"]

# Rules to be ignored
ignore = [
    "ANN002",
    "D100", 
    "EM101", 
    "E701",
    "TRY003",
    "FBT001",
    "FBT002",
    "EM101",
    "Q000",
    "ISC002",
    "D103",
    "D102",
    "D107",
    "T201",
    "ANN201",
    "ANN204",
    "PLW0602",
    "PLW0603",
]