services:
  db1:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teamninelives
      MYSQL_DATABASE: VendingMachineDB
      MYSQL_ROOT_HOST: '%'
    volumes:
      - vendingmachinedat:/var/lib/mysql   # Persistent database storage
      - /nobackup/vending-machine-db/:/docker-entrypoint-initdb.d/  # Run init script on startup
    ports:
      - "3333:3306"

volumes:
  vendingmachinedat: