services:
  db1:
    image: mysql/mysql-server:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teamninelives
      MYSQL_DATABASE: VendingMachineDB
      MYSQL_ROOT_HOST: '%'
    volumes:
      - vendingmachinedat:/var/lib/mysql   # Persistent database storage
      - /nobackup/vending-machine-db/:/docker-entrypoint-initdb.d/  # Run init script on startup
    ports:
      - "3333:3306"

  backend:
    build: ./api
    restart: always
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "8080:5000"
    depends_on:
      - db1
    env_file:
      - ./api/.env

volumes:
  vendingmachinedat: